### ISSUE TITLE
Successful payments not showin in "All Orders"

### ISSUE THREAD

**Issue by highchoice** [naa986/wp-stripe-checkout#3]
I'm using two version of short-codes.

First one 
[wp_stripe_checkout id="MyProductID#"]
All workflow is working fine, but successful orders are not appearing on all orders lists!
Second one 
[wp_stripe_checkout item_name="Product Name" description="Product description" billing-address="true" shipping-address="true" zip-code="true" amount="59.99" label="Pay Now"]
Everything works as expected, I can see completed orders in list.

**Comment by highchoice** [comment]
I realized where I was wrong. I did not create webhooks in test mode

**Comment by nsmith1024** [comment]
what about the wordpress userID of the person who ordered? how are we supposed to know from the data returned on the webhook who ordered what?
